name: chat_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # Firebase core package for initialization
  firebase_core: ^2.0.0

  #add storage

  # Firebase Authentication for user management
  firebase_auth: ^4.0.0

  # Firestore for real-time database management
  cloud_firestore: ^4.0.0

  # add storage

  # BLoC library for state management
  flutter_bloc: ^8.0.1

  # Encryption library for secure communication
  encrypt: ^5.0.1

  # Equatable for easy comparison
  equatable: ^2.0.4

  intl: ^0.17.0

  intl_phone_number_input: ^0.7.3+1

  flutter_spinkit: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
